In [ ]:
import networkx as nx
import numpy as np

In [ ]:

def generate_random_graph(num_vertices, num_edges):
    G = nx.gnm_random_graph(num_vertices, num_edges,directed=True)
    return G

In [ ]:
def google_matrix(G, alpha=0.80):
    M = np.asmatrix(nx.to_numpy_array(G))
    N = len(G)
    if N == 0:
        return M

    # Personalization vector
    p = np.repeat(1.0 / N, N)

    # Dangling nodes
    dangling_weights = p
    dangling_nodes = np.where(M.sum(axis=1) == 0)[0]

    # Assign dangling_weights to any dangling nodes
    # (nodes with no out links)
    for node in dangling_nodes:
        M[node] = dangling_weights
    print(M)
    M /= M.sum(axis=1)  # Normalize rows to sum to 1

    return alpha * M + (1 - alpha) * p

In [ ]:
def pagerank_numpy(G, alpha=0.80):
    if len(G) == 0:
        return {}
    M = google_matrix(G, alpha)

    # use numpy LAPACK solver
    eigenvalues, eigenvectors = np.linalg.eig(M.T)
    ind = np.argmax(eigenvalues)








    # eigenvector of largest eigenvalue is at ind, normalized
    largest = np.array(eigenvectors[:, ind]).flatten().real
    norm = float(largest.sum())
    return dict(zip(G, map(float, largest / norm)))

In [ ]:
num_vertices = 100
num_edges = 1000

G = generate_random_graph(num_vertices, num_edges)
pagerank_scores = pagerank_numpy(G, alpha=0.80)

# Print top 10 scores
top_scores = sorted(pagerank_scores.items(), key=lambda x: x[1], reverse=True)[:10]
print("Top 10 PageRank Scores:")
for node, score in top_scores:
    print(f"{node}: {score*100}")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Top 10 PageRank Scores:
70: 1.7519414949508383
57: 1.690176403007802
99: 1.5231817899758402
16: 1.5022330270116018
25: 1.4568316414321147
35: 1.4516532180126431
9: 1.4452298578610439
5: 1.439037099144808
13: 1.428340796360815
81: 1.4163305525134693
